#!/usr/bin/env python3
"""Update all locale JSON files with complete translation keys."""
import json
import os

BASE = os.path.join(os.path.dirname(__file__), '..', 'lib', 'locales')

# ──────────────────────────────────────────────────────────
# ENGLISH (base)
# ──────────────────────────────────────────────────────────
EN = {
  "nav": {"main": "Main", "community": "Community", "services": "Services", "help": "Help", "myPage": "My Page"},
  "common": {"loading": "Loading...", "save": "Save", "cancel": "Cancel", "delete": "Delete", "edit": "Edit", "close": "Close", "send": "Send", "submit": "Submit", "confirm": "Confirm", "back": "Back", "search": "Search", "language": "Language", "check": "Check", "verify": "Verify", "by": "by", "justNow": "just now", "minutesAgo": "{{count}}m ago", "hoursAgo": "{{count}}h ago", "daysAgo": "{{count}}d ago", "unknown": "Unknown", "exploreCommunity": "Go to Community →"},
  "auth": {"login": "Login", "logout": "Logout", "signUp": "Sign Up", "loginRequired": "Login required", "loginRequiredDesc": "You need to be logged in to view this page.", "loggingIn": "Logging in...", "loginSuccess": "Login successful!", "email": "Email", "password": "Password", "enterEmail": "Enter your email", "enterPassword": "Enter your password", "emailRequired": "Please enter your email.", "passwordRequired": "Please enter your password.", "loginFailed": "Login failed. Please try again.", "findId": "Find ID", "resetPasswordLink": "Reset Password"},
  "community": {"title": "Community", "writePost": "Write a Post", "comments": "Comments", "noComments": "No comments yet.", "commentPlaceholder": "Write a comment...", "loginToComment": "Login required to comment.", "picture": "Picture", "noPostsYet": "No posts yet.", "postNotFound": "Post not found", "report": "Report", "blockUser": "Block user", "unblockUser": "Unblock user", "youAreBlocked": "You have blocked this user", "edit": "Edit", "delete": "Delete", "editPost": "Edit Post", "deleteConfirm": "Are you sure you want to delete this?", "saving": "Saving...", "userProfile": "User Profile", "userNotFound": "User not found.", "posts": "Posts", "noPostsAvailable": "No posts available.", "failedToLoad": "Failed to load posts", "removeImage": "× Remove", "blockAlready": "This user is already blocked.", "blockFailed": "Failed to block user. Please try again.", "blockSuccess": "User has been blocked.", "unblockFailed": "Failed to unblock user. Please try again.", "unblockSuccess": "User has been unblocked.", "categories": {"all": "All Posts", "food": "Food 🍚", "housing": "Housing 🏠", "school": "School 🏫", "job": "Job 👨‍💻", "hospital": "Hospital 🏥", "info": "Info 💁", "free": "Free 🍀"}},
  "home": {"recentPosts": "Recent Posts", "trendingPosts": "Trending Posts", "noRecentPosts": "No recent posts yet.", "noTrendingPosts": "No trending posts right now.", "banners": {"policy": {"title": "Support Policies for Foreigners", "desc": "2024 New Policies and Funding Information"}, "visa": {"title": "Visa & Residence Updates", "desc": "Latest Visa Regulations and Changes"}, "services": {"title": "Services for Internationals", "desc": "Discover All ANNYEONG Services"}, "announcements": {"title": "ANNYEONG Announcements", "desc": "Community Updates & New Features"}}},
  "myPage": {"title": "My Profile", "myPosts": "My Posts", "likedPosts": "Liked Posts", "friends": "Friends", "settings": "Settings", "myPostsDesc": "Posts you've published", "likedPostsDesc": "Posts you've liked", "friendsDesc": "Friends & blocked users", "settingsDesc": "Profile, password, language", "signInPrompt": "Sign in to view your profile", "noPosts": "No posts yet.", "noLikedPosts": "No liked posts yet.", "noPostsWritten": "You haven't written any posts yet.", "noPostsLiked": "You haven't liked any posts yet."},
  "settings": {"title": "Settings", "editProfile": "Edit Profile", "editProfileDesc": "Nickname, flag, and profile photo", "editProfileTitle": "Edit Profile", "resetPassword": "Reset Password", "resetPasswordDesc": "Update your password", "resetPasswordTitle": "Reset Password", "chooseLanguage": "Choose Language", "chooseLanguageDesc": "Choose your preferred language", "chooseLanguageHint": "Choose the language used for content translation and preferences.", "confirmSelection": "Confirm Selection", "languageUpdated": "Language updated!", "saving": "Saving...", "profilePhoto": "Profile Photo", "choosePhoto": "📷 Choose Photo", "nickname": "Nickname", "nicknamePlaceholder": "Your nickname", "nicknameEmpty": "Nickname cannot be empty.", "imageUploadFailed": "Image upload failed. Please try again.", "saveFailed": "Failed to save. Please try again.", "savedSuccess": "Saved successfully!", "saveChanges": "Save Changes", "currentPassword": "Current Password", "currentPasswordPlaceholder": "Enter your current password", "newPassword": "New Password", "newPasswordPlaceholder": "At least 6 characters", "confirmNewPassword": "Confirm New Password", "confirmNewPasswordPlaceholder": "Re-enter new password", "verifyBtn": "Verify", "verifying": "Verifying...", "verified": "✓ Password verified", "incorrectPassword": "Current password is incorrect.", "passwordRequired": "Please enter your current password.", "enterNewPasswordBelow": "Enter your new password below.", "passwordMismatch": "Passwords do not match.", "updatePassword": "Update Password", "updating": "Updating...", "passwordUpdated": "Password updated successfully!"},
  "friends": {"title": "Friends", "friendsTab": "Friends", "blockedTab": "Blocked users", "friendsComingSoon": "Friends feature coming soon.", "noBlocked": "No blocked users.", "unblock": "Unblock", "unblocking": "Unblocking...", "loginToView": "Login to view your friends and blocked users."},
  "report": {"title": "Report", "reason": "Reason", "reasonPlaceholder": "Select a reason", "description": "Details (optional)", "descriptionPlaceholder": "Please describe the issue in detail...", "attachImage": "📷 Attach Image", "removeImage": "× Remove", "submit": "Submit Report", "submitting": "Submitting...", "cancel": "Cancel", "successTitle": "Report submitted.", "successDesc": "We will review and take action.", "duplicatePost": "You have already reported this post.", "duplicateComment": "You have already reported this comment.", "errorGeneric": "An error occurred. Please try again.", "selectReason": "Please select a reason.", "reasons": {"hate": "Hate / Offensive language", "sexual": "Sexual harassment", "spam": "Spam / Advertisement", "scam": "Scam / Suspicious activity", "misinformation": "Misinformation", "privacy": "Privacy violation", "illegal": "Illegal / Dangerous content", "other": "Other"}},
  "help": {"title": "Help & Support", "faqTitle": "Frequently Asked Questions", "shareIdeasTitle": "Share Your Ideas", "shareIdeasDesc": "Have a feature or service idea? Tell us! Good ideas are implemented and adopted suggestions earn rewards.", "shareIdeasBtn": "Share Your Idea", "needHelpTitle": "Need More Help?", "needHelpDesc": "Can't find what you're looking for? Contact our team anytime.", "contactBtn": "Contact Our Team", "faqs": {"q1": "Is ANNYEONG really free?", "a1": "Community access and basic info are completely free. Some premium services may have costs, but initial consultation is always free.", "q2": "How long does it take to get help?", "a2": "We respond within 1-2 hours for most inquiries. For urgent matters, we prioritize faster responses.", "q3": "What documents do I need for a visa?", "a3": "It depends on your visa type. We offer personalized guidance - join the community or contact us for specific requirements.", "q4": "Can I use ANNYEONG before arriving in Korea?", "a4": "Absolutely! Our platform helps people prepare before they arrive, so you can get a head start on settling in.", "q5": "What languages are supported?", "a5": "We support Korean, English, Chinese, Japanese, Vietnamese. More languages coming soon!"}, "shareIdea": {"title": "💡 Share Your Idea", "ideaTitle": "Title", "ideaTitlePlaceholder": "Your idea in one line", "featureArea": "Feature Area", "featureAreaPlaceholder": "Select...", "description": "Description", "descriptionPlaceholder": "Describe your idea in detail...", "photo": "Photo (optional)", "uploadImage": "📷 Upload Image", "submitBtn": "Submit Idea", "submitting": "Submitting...", "fillRequired": "Please fill in all required fields.", "submitFailed": "Failed to submit. Please try again.", "successTitle": "Thanks for your idea!", "successDesc": "We'll review it soon.", "featureOptions": {"community": "Community", "service": "Service", "other": "Other"}}, "needHelp": {"title": "🤝 Need More Help?", "ideaTitle": "Title", "ideaTitlePlaceholder": "Brief summary of your issue", "details": "Details", "detailsPlaceholder": "Please describe what you need help with...", "contact": "Email / Contact (optional)", "contactPlaceholder": "Where should we reach you?", "photo": "Photo (optional)", "uploadImage": "📷 Upload Image", "sendBtn": "Send Request", "sending": "Sending...", "fillRequired": "Please fill in all required fields.", "sendFailed": "Failed to send. Please try again.", "successTitle": "Your request has been sent!", "successDesc": "Our team will get back to you soon.", "topics": {"visa": "Visa / Residence", "housing": "Housing", "job": "Job / Work", "school": "School / Education", "health": "Health / Hospital", "other": "Other"}}},
  "signup": {"title": "Sign Up", "email": "Email", "password": "Password", "nickname": "Nickname", "country": "Country", "preferredLanguage": "Preferred Language", "purpose": "Purpose", "status": "Status", "check": "Check", "signingUp": "Signing Up...", "cancel": "Cancel", "emailRequired": "Please check that your email is available.", "nicknameRequired": "Please check that your nickname is available.", "passwordRequired": "Please enter a password.", "failed": "Sign up failed. Please try again.", "success": "Sign up completed successfully.", "emailCheckFailed": "Failed to check email. Please try again.", "nicknameCheckFailed": "Failed to check nickname. Please try again.", "enterEmail": "Please enter an email.", "enterNickname": "Please enter a nickname.", "confirmLanguageTitle": "Confirm Language Selection", "confirm": "Confirm", "purposeOptions": {"community": "Community", "service": "Service", "information": "Information"}, "statusOptions": {"living": "Currently Living in Korea", "planning": "Planning to Move to Korea"}},
  "findId": {"title": "Find ID", "desc": "Please enter the nickname you used when signing up.", "nicknamePlaceholder": "Your nickname", "find": "Find", "searching": "Searching...", "close": "Close", "enterNickname": "Please enter your nickname.", "notFound": "Nickname not found. Please check and try again.", "failed": "Failed to find ID. Please try again.", "yourEmail": "Your email"},
  "resetPassword": {"title": "Reset Password", "step1Desc": "Enter the email associated with your account.", "codeSentTo": "Verification code sent to", "step2Desc": "Enter the 6-digit verification code sent to your email.", "step3Desc": "Enter your new password.", "newPassword": "New Password", "confirmPassword": "Confirm Password", "sendCode": "Send Verification Code", "sending": "Sending...", "back": "Back", "verify": "Verify", "verifying": "Verifying...", "resetBtn": "Reset Password", "resetting": "Resetting...", "successTitle": "Password Reset Successful", "successDesc": "Your password has been successfully reset. Please log in with your new password.", "enterEmail": "Please enter your email.", "enterCode": "Please enter the verification code.", "codeLength": "Verification code must be 8 digits.", "codeExpired": "Verification code has expired. Please request a new one.", "codeInvalid": "Invalid verification code. Please check and try again.", "sendFailed": "Failed to send verification code. Please try again.", "verifyFailed": "Verification failed. Please try again.", "enterNewPassword": "Please enter a new password.", "passwordMismatch": "Passwords do not match.", "resetFailed": "Failed to reset password. Please try again."},
  "writePost": {"title": "Write a Post", "category": "Category", "categoryPlaceholder": "Select a category", "postTitle": "Title", "titlePlaceholder": "Enter a title", "content": "Content", "contentPlaceholder": "Write your post...", "photo": "Photo (optional)", "uploadImage": "📷 Upload Image", "submit": "Submit", "saving": "Saving...", "fillRequired": "Please fill all required fields.", "failed": "Failed to save post."},
  "languages": {"en": "English", "ko": "Korean", "zh": "Chinese", "ja": "Japanese", "es": "Spanish", "vi": "Vietnamese"}
}

# ──────────────────────────────────────────────────────────
# KOREAN
# ──────────────────────────────────────────────────────────
KO = {
  "nav": {"main": "메인", "community": "커뮤니티", "services": "서비스", "help": "도움말", "myPage": "마이페이지"},
  "common": {"loading": "로딩 중...", "save": "저장", "cancel": "취소", "delete": "삭제", "edit": "수정", "close": "닫기", "send": "전송", "submit": "제출", "confirm": "확인", "back": "뒤로", "search": "검색", "language": "언어", "check": "확인", "verify": "인증", "by": "작성자", "justNow": "방금 전", "minutesAgo": "{{count}}분 전", "hoursAgo": "{{count}}시간 전", "daysAgo": "{{count}}일 전", "unknown": "알 수 없음", "exploreCommunity": "커뮤니티 보기 →"},
  "auth": {"login": "로그인", "logout": "로그아웃", "signUp": "회원가입", "loginRequired": "로그인 필요", "loginRequiredDesc": "이 페이지를 보려면 로그인이 필요합니다.", "loggingIn": "로그인 중...", "loginSuccess": "로그인 성공!", "email": "이메일", "password": "비밀번호", "enterEmail": "이메일을 입력하세요", "enterPassword": "비밀번호를 입력하세요", "emailRequired": "이메일을 입력해 주세요.", "passwordRequired": "비밀번호를 입력해 주세요.", "loginFailed": "로그인에 실패했습니다. 다시 시도해 주세요.", "findId": "아이디 찾기", "resetPasswordLink": "비밀번호 재설정"},
  "community": {"title": "커뮤니티", "writePost": "게시글 작성", "comments": "댓글", "noComments": "아직 댓글이 없습니다.", "commentPlaceholder": "댓글을 입력하세요...", "loginToComment": "댓글을 작성하려면 로그인이 필요합니다.", "picture": "사진", "noPostsYet": "게시글이 없습니다.", "postNotFound": "게시글을 찾을 수 없습니다", "report": "신고", "blockUser": "유저 차단", "unblockUser": "차단 해제", "youAreBlocked": "이 사용자를 차단했습니다", "edit": "수정", "delete": "삭제", "editPost": "게시글 수정", "deleteConfirm": "정말 삭제하시겠습니까?", "saving": "저장 중...", "userProfile": "사용자 프로필", "userNotFound": "사용자를 찾을 수 없습니다.", "posts": "게시글", "noPostsAvailable": "게시글이 없습니다.", "failedToLoad": "게시글을 불러오지 못했습니다", "removeImage": "× 제거", "blockAlready": "이미 차단한 사용자입니다.", "blockFailed": "차단에 실패했습니다. 다시 시도해 주세요.", "blockSuccess": "사용자를 차단했습니다.", "unblockFailed": "차단 해제에 실패했습니다. 다시 시도해 주세요.", "unblockSuccess": "차단이 해제되었습니다.", "categories": {"all": "전체 게시글", "food": "음식 🍚", "housing": "주거 🏠", "school": "학교 🏫", "job": "취업 👨‍💻", "hospital": "병원 🏥", "info": "정보 💁", "free": "자유 🍀"}},
  "home": {"recentPosts": "최근 게시글", "trendingPosts": "인기 게시글", "noRecentPosts": "아직 게시글이 없습니다.", "noTrendingPosts": "지금 인기 게시글이 없습니다.", "banners": {"policy": {"title": "외국인 지원 정책", "desc": "2024 새 정책 및 지원 정보"}, "visa": {"title": "비자 & 체류 업데이트", "desc": "최신 비자 규정 및 변경 사항"}, "services": {"title": "외국인을 위한 서비스", "desc": "ANNYEONG의 모든 서비스 알아보기"}, "announcements": {"title": "ANNYEONG 공지", "desc": "커뮤니티 업데이트 & 새 기능"}}},
  "myPage": {"title": "내 프로필", "myPosts": "내 게시글", "likedPosts": "좋아요한 게시글", "friends": "친구", "settings": "설정", "myPostsDesc": "내가 작성한 게시글", "likedPostsDesc": "좋아요한 게시글", "friendsDesc": "친구 & 차단한 사용자", "settingsDesc": "프로필, 비밀번호, 언어", "signInPrompt": "프로필을 보려면 로그인하세요", "noPosts": "작성한 게시글이 없습니다.", "noLikedPosts": "좋아요한 게시글이 없습니다.", "noPostsWritten": "아직 작성한 게시글이 없습니다.", "noPostsLiked": "아직 좋아요한 게시글이 없습니다."},
  "settings": {"title": "설정", "editProfile": "프로필 편집", "editProfileDesc": "닉네임, 국기, 프로필 사진", "editProfileTitle": "프로필 편집", "resetPassword": "비밀번호 재설정", "resetPasswordDesc": "비밀번호를 변경하세요", "resetPasswordTitle": "비밀번호 재설정", "chooseLanguage": "언어 선택", "chooseLanguageDesc": "선호하는 언어를 선택하세요", "chooseLanguageHint": "번역 및 설정에 사용할 언어를 선택하세요.", "confirmSelection": "선택 완료", "languageUpdated": "언어가 변경되었습니다!", "saving": "저장 중...", "profilePhoto": "프로필 사진", "choosePhoto": "📷 사진 선택", "nickname": "닉네임", "nicknamePlaceholder": "닉네임을 입력하세요", "nicknameEmpty": "닉네임은 비워둘 수 없습니다.", "imageUploadFailed": "이미지 업로드에 실패했습니다. 다시 시도해 주세요.", "saveFailed": "저장에 실패했습니다. 다시 시도해 주세요.", "savedSuccess": "저장되었습니다!", "saveChanges": "변경 사항 저장", "currentPassword": "현재 비밀번호", "currentPasswordPlaceholder": "현재 비밀번호를 입력하세요", "newPassword": "새 비밀번호", "newPasswordPlaceholder": "6자 이상 입력하세요", "confirmNewPassword": "새 비밀번호 확인", "confirmNewPasswordPlaceholder": "새 비밀번호를 다시 입력하세요", "verifyBtn": "인증", "verifying": "인증 중...", "verified": "✓ 비밀번호 확인 완료", "incorrectPassword": "현재 비밀번호가 올바르지 않습니다.", "passwordRequired": "현재 비밀번호를 입력해 주세요.", "enterNewPasswordBelow": "새 비밀번호를 입력하세요.", "passwordMismatch": "비밀번호가 일치하지 않습니다.", "updatePassword": "비밀번호 변경", "updating": "변경 중...", "passwordUpdated": "비밀번호가 성공적으로 변경되었습니다!"},
  "friends": {"title": "친구", "friendsTab": "친구", "blockedTab": "차단한 사용자", "friendsComingSoon": "친구 기능은 준비 중입니다.", "noBlocked": "차단한 사용자가 없습니다.", "unblock": "차단 해제", "unblocking": "해제 중...", "loginToView": "친구 및 차단 목록을 보려면 로그인하세요."},
  "report": {"title": "신고하기", "reason": "신고 사유", "reasonPlaceholder": "사유를 선택해 주세요", "description": "상세 내용 (선택)", "descriptionPlaceholder": "상세한 내용을 입력해 주세요...", "attachImage": "📷 이미지 첨부", "removeImage": "× 제거", "submit": "신고하기", "submitting": "제출 중...", "cancel": "취소", "successTitle": "신고가 접수되었습니다.", "successDesc": "검토 후 조치하겠습니다.", "duplicatePost": "이미 신고한 게시글입니다.", "duplicateComment": "이미 신고한 댓글입니다.", "errorGeneric": "오류가 발생했습니다. 다시 시도해 주세요.", "selectReason": "신고 사유를 선택해 주세요.", "reasons": {"hate": "욕설 / 혐오 표현", "sexual": "성희롱 / 성적 불쾌감", "spam": "스팸 / 광고", "scam": "사기 / 의심스러운 거래", "misinformation": "허위 정보 / 오해 유발", "privacy": "개인정보 노출", "illegal": "불법 / 위험한 내용", "other": "기타"}},
  "help": {"title": "도움말 & 지원", "faqTitle": "자주 묻는 질문", "shareIdeasTitle": "아이디어 공유", "shareIdeasDesc": "기능이나 서비스 아이디어가 있으신가요? 알려주세요! 좋은 아이디어는 실제로 반영되며 채택된 제안은 보상을 받습니다.", "shareIdeasBtn": "아이디어 공유하기", "needHelpTitle": "더 도움이 필요하신가요?", "needHelpDesc": "원하는 내용을 찾지 못하셨나요? 언제든지 팀에 문의하세요.", "contactBtn": "팀에 문의하기", "faqs": {"q1": "ANNYEONG은 정말 무료인가요?", "a1": "커뮤니티 이용과 기본 정보는 완전히 무료입니다. 일부 프리미엄 서비스는 비용이 발생할 수 있지만, 초기 상담은 항상 무료입니다.", "q2": "도움을 받는 데 얼마나 걸리나요?", "a2": "대부분의 문의에 1-2시간 내에 응답합니다. 긴급한 경우 더 빠른 응대를 우선합니다.", "q3": "비자에 필요한 서류는 무엇인가요?", "a3": "비자 종류에 따라 다릅니다. 커뮤니티에 참여하거나 문의하시면 맞춤 안내를 드립니다.", "q4": "한국에 오기 전에도 ANNYEONG을 사용할 수 있나요?", "a4": "물론입니다! 저희 플랫폼은 입국 전 준비를 돕기 위해 만들어졌습니다.", "q5": "어떤 언어를 지원하나요?", "a5": "한국어, 영어, 중국어, 일본어, 베트남어를 지원합니다. 더 많은 언어가 곧 추가됩니다!"}, "shareIdea": {"title": "💡 아이디어 공유하기", "ideaTitle": "제목", "ideaTitlePlaceholder": "한 줄로 아이디어를 입력하세요", "featureArea": "기능 영역", "featureAreaPlaceholder": "선택...", "description": "설명", "descriptionPlaceholder": "아이디어를 자세히 설명해 주세요...", "photo": "사진 (선택)", "uploadImage": "📷 이미지 업로드", "submitBtn": "아이디어 제출", "submitting": "제출 중...", "fillRequired": "모든 필수 항목을 입력해 주세요.", "submitFailed": "제출에 실패했습니다. 다시 시도해 주세요.", "successTitle": "아이디어 감사합니다!", "successDesc": "빠르게 검토하겠습니다.", "featureOptions": {"community": "커뮤니티", "service": "서비스", "other": "기타"}}, "needHelp": {"title": "🤝 더 도움이 필요하신가요?", "ideaTitle": "제목", "ideaTitlePlaceholder": "문제를 간략히 요약해 주세요", "details": "세부 내용", "detailsPlaceholder": "도움이 필요한 내용을 자세히 설명해 주세요...", "contact": "이메일 / 연락처 (선택)", "contactPlaceholder": "어디로 연락드릴까요?", "photo": "사진 (선택)", "uploadImage": "📷 이미지 업로드", "sendBtn": "요청 보내기", "sending": "전송 중...", "fillRequired": "모든 필수 항목을 입력해 주세요.", "sendFailed": "전송에 실패했습니다. 다시 시도해 주세요.", "successTitle": "요청이 전송되었습니다!", "successDesc": "팀이 곧 연락드리겠습니다.", "topics": {"visa": "비자 / 체류", "housing": "주거", "job": "취업 / 업무", "school": "학교 / 교육", "health": "건강 / 병원", "other": "기타"}}},
  "signup": {"title": "회원가입", "email": "이메일", "password": "비밀번호", "nickname": "닉네임", "country": "국가", "preferredLanguage": "선호 언어", "purpose": "목적", "status": "현재 상태", "check": "확인", "signingUp": "가입 중...", "cancel": "취소", "emailRequired": "이메일 사용 가능 여부를 확인해 주세요.", "nicknameRequired": "닉네임 사용 가능 여부를 확인해 주세요.", "passwordRequired": "비밀번호를 입력해 주세요.", "failed": "회원가입에 실패했습니다. 다시 시도해 주세요.", "success": "회원가입이 완료되었습니다.", "emailCheckFailed": "이메일 확인에 실패했습니다. 다시 시도해 주세요.", "nicknameCheckFailed": "닉네임 확인에 실패했습니다. 다시 시도해 주세요.", "enterEmail": "이메일을 입력해 주세요.", "enterNickname": "닉네임을 입력해 주세요.", "confirmLanguageTitle": "언어 선택 확인", "confirm": "확인", "purposeOptions": {"community": "커뮤니티", "service": "서비스", "information": "정보"}, "statusOptions": {"living": "현재 한국 거주 중", "planning": "한국 이주 예정"}},
  "findId": {"title": "아이디 찾기", "desc": "가입 시 사용한 닉네임을 입력해 주세요.", "nicknamePlaceholder": "닉네임", "find": "찾기", "searching": "검색 중...", "close": "닫기", "enterNickname": "닉네임을 입력해 주세요.", "notFound": "닉네임을 찾을 수 없습니다. 다시 확인해 주세요.", "failed": "아이디 찾기에 실패했습니다. 다시 시도해 주세요.", "yourEmail": "회원님의 이메일"},
  "resetPassword": {"title": "비밀번호 재설정", "step1Desc": "계정에 등록된 이메일을 입력하세요.", "codeSentTo": "인증 코드 발송 완료:", "step2Desc": "이메일로 발송된 인증 코드를 입력하세요.", "step3Desc": "새 비밀번호를 입력하세요.", "newPassword": "새 비밀번호", "confirmPassword": "비밀번호 확인", "sendCode": "인증 코드 발송", "sending": "발송 중...", "back": "뒤로", "verify": "인증", "verifying": "인증 중...", "resetBtn": "비밀번호 재설정", "resetting": "재설정 중...", "successTitle": "비밀번호 재설정 완료", "successDesc": "비밀번호가 성공적으로 재설정되었습니다. 새 비밀번호로 로그인해 주세요.", "enterEmail": "이메일을 입력해 주세요.", "enterCode": "인증 코드를 입력해 주세요.", "codeLength": "인증 코드는 8자리여야 합니다.", "codeExpired": "인증 코드가 만료되었습니다. 새로 요청해 주세요.", "codeInvalid": "잘못된 인증 코드입니다. 다시 확인해 주세요.", "sendFailed": "인증 코드 발송에 실패했습니다. 다시 시도해 주세요.", "verifyFailed": "인증에 실패했습니다. 다시 시도해 주세요.", "enterNewPassword": "새 비밀번호를 입력해 주세요.", "passwordMismatch": "비밀번호가 일치하지 않습니다.", "resetFailed": "비밀번호 재설정에 실패했습니다. 다시 시도해 주세요."},
  "writePost": {"title": "게시글 작성", "category": "카테고리", "categoryPlaceholder": "카테고리 선택", "postTitle": "제목", "titlePlaceholder": "제목을 입력하세요", "content": "내용", "contentPlaceholder": "내용을 입력하세요...", "photo": "사진 (선택)", "uploadImage": "📷 이미지 업로드", "submit": "제출", "saving": "저장 중...", "fillRequired": "모든 필수 항목을 입력해 주세요.", "failed": "게시글 저장에 실패했습니다."},
  "languages": {"en": "영어", "ko": "한국어", "zh": "중국어", "ja": "일본어", "es": "스페인어", "vi": "베트남어"}
}

# ──────────────────────────────────────────────────────────
# CHINESE
# ──────────────────────────────────────────────────────────
ZH = {
  "nav": {"main": "主页", "community": "社区", "services": "服务", "help": "帮助", "myPage": "我的主页"},
  "common": {"loading": "加载中...", "save": "保存", "cancel": "取消", "delete": "删除", "edit": "编辑", "close": "关闭", "send": "发送", "submit": "提交", "confirm": "确认", "back": "返回", "search": "搜索", "language": "语言", "check": "确认", "verify": "验证", "by": "作者", "justNow": "刚刚", "minutesAgo": "{{count}}分钟前", "hoursAgo": "{{count}}小时前", "daysAgo": "{{count}}天前", "unknown": "未知", "exploreCommunity": "去社区 →"},
  "auth": {"login": "登录", "logout": "退出", "signUp": "注册", "loginRequired": "需要登录", "loginRequiredDesc": "您需要登录才能查看此页面。", "loggingIn": "登录中...", "loginSuccess": "登录成功！", "email": "邮箱", "password": "密码", "enterEmail": "请输入邮箱", "enterPassword": "请输入密码", "emailRequired": "请输入邮箱。", "passwordRequired": "请输入密码。", "loginFailed": "登录失败，请重试。", "findId": "找回账号", "resetPasswordLink": "重置密码"},
  "community": {"title": "社区", "writePost": "写帖子", "comments": "评论", "noComments": "暂无评论。", "commentPlaceholder": "写一条评论...", "loginToComment": "需要登录才能评论。", "picture": "图片", "noPostsYet": "暂无帖子。", "postNotFound": "找不到帖子", "report": "举报", "blockUser": "屏蔽用户", "unblockUser": "取消屏蔽", "youAreBlocked": "您已屏蔽该用户", "edit": "编辑", "delete": "删除", "editPost": "编辑帖子", "deleteConfirm": "确定要删除吗？", "saving": "保存中...", "userProfile": "用户资料", "userNotFound": "找不到用户。", "posts": "帖子", "noPostsAvailable": "暂无帖子。", "failedToLoad": "加载帖子失败", "removeImage": "× 删除", "blockAlready": "您已屏蔽此用户。", "blockFailed": "屏蔽失败，请重试。", "blockSuccess": "用户已被屏蔽。", "unblockFailed": "取消屏蔽失败，请重试。", "unblockSuccess": "已取消屏蔽。", "categories": {"all": "全部帖子", "food": "美食 🍚", "housing": "住房 🏠", "school": "学校 🏫", "job": "工作 👨‍💻", "hospital": "医院 🏥", "info": "信息 💁", "free": "自由 🍀"}},
  "home": {"recentPosts": "最新帖子", "trendingPosts": "热门帖子", "noRecentPosts": "暂无最新帖子。", "noTrendingPosts": "目前没有热门帖子。", "banners": {"policy": {"title": "外国人支持政策", "desc": "2024年新政策和资金信息"}, "visa": {"title": "签证和居留更新", "desc": "最新签证法规和变化"}, "services": {"title": "国际人士服务", "desc": "探索所有ANNYEONG服务"}, "announcements": {"title": "ANNYEONG公告", "desc": "社区更新和新功能"}}},
  "myPage": {"title": "我的资料", "myPosts": "我的帖子", "likedPosts": "点赞帖子", "friends": "好友", "settings": "设置", "myPostsDesc": "您发布的帖子", "likedPostsDesc": "您点赞的帖子", "friendsDesc": "好友与屏蔽用户", "settingsDesc": "资料、密码、语言", "signInPrompt": "登录查看您的资料", "noPosts": "暂无帖子。", "noLikedPosts": "暂无点赞帖子。", "noPostsWritten": "您还没有写过帖子。", "noPostsLiked": "您还没有点赞任何帖子。"},
  "settings": {"title": "设置", "editProfile": "编辑资料", "editProfileDesc": "昵称、国旗、头像", "editProfileTitle": "编辑资料", "resetPassword": "重置密码", "resetPasswordDesc": "更新您的密码", "resetPasswordTitle": "重置密码", "chooseLanguage": "选择语言", "chooseLanguageDesc": "选择您偏好的语言", "chooseLanguageHint": "选择用于内容翻译和偏好设置的语言。", "confirmSelection": "确认选择", "languageUpdated": "语言已更新！", "saving": "保存中...", "profilePhoto": "头像", "choosePhoto": "📷 选择照片", "nickname": "昵称", "nicknamePlaceholder": "请输入昵称", "nicknameEmpty": "昵称不能为空。", "imageUploadFailed": "图片上传失败，请重试。", "saveFailed": "保存失败，请重试。", "savedSuccess": "保存成功！", "saveChanges": "保存更改", "currentPassword": "当前密码", "currentPasswordPlaceholder": "请输入当前密码", "newPassword": "新密码", "newPasswordPlaceholder": "至少6个字符", "confirmNewPassword": "确认新密码", "confirmNewPasswordPlaceholder": "再次输入新密码", "verifyBtn": "验证", "verifying": "验证中...", "verified": "✓ 密码已验证", "incorrectPassword": "当前密码不正确。", "passwordRequired": "请输入当前密码。", "enterNewPasswordBelow": "请在下方输入新密码。", "passwordMismatch": "密码不一致。", "updatePassword": "更新密码", "updating": "更新中...", "passwordUpdated": "密码已成功更新！"},
  "friends": {"title": "好友", "friendsTab": "好友", "blockedTab": "已屏蔽用户", "friendsComingSoon": "好友功能即将上线。", "noBlocked": "暂无屏蔽用户。", "unblock": "取消屏蔽", "unblocking": "处理中...", "loginToView": "登录以查看好友和屏蔽用户。"},
  "report": {"title": "举报", "reason": "举报原因", "reasonPlaceholder": "请选择原因", "description": "详细说明（可选）", "descriptionPlaceholder": "请详细描述问题...", "attachImage": "📷 附加图片", "removeImage": "× 删除", "submit": "提交举报", "submitting": "提交中...", "cancel": "取消", "successTitle": "举报已提交。", "successDesc": "我们将审核并采取措施。", "duplicatePost": "您已举报过此帖子。", "duplicateComment": "您已举报过此评论。", "errorGeneric": "发生错误，请重试。", "selectReason": "请选择举报原因。", "reasons": {"hate": "仇恨 / 冒犯性语言", "sexual": "性骚扰", "spam": "垃圾信息 / 广告", "scam": "诈骗 / 可疑活动", "misinformation": "虚假信息", "privacy": "隐私泄露", "illegal": "违法 / 危险内容", "other": "其他"}},
  "help": {"title": "帮助 & 支持", "faqTitle": "常见问题", "shareIdeasTitle": "分享您的想法", "shareIdeasDesc": "有功能或服务建议？告诉我们！好的建议会被采纳，采纳的想法可获得奖励。", "shareIdeasBtn": "分享想法", "needHelpTitle": "需要更多帮助？", "needHelpDesc": "找不到您需要的内容？随时联系我们的团队。", "contactBtn": "联系团队", "faqs": {"q1": "ANNYEONG真的是免费的吗？", "a1": "社区访问和基本信息完全免费。部分高级服务可能收费，但初次咨询始终免费。", "q2": "获得帮助需要多长时间？", "a2": "大多数问题我们会在1-2小时内回复。紧急情况会优先处理。", "q3": "申请签证需要哪些文件？", "a3": "取决于您的签证类型。加入社区或联系我们，我们会提供个性化指导。", "q4": "来韩国之前可以使用ANNYEONG吗？", "a4": "当然！我们的平台帮助人们提前做好准备。", "q5": "支持哪些语言？", "a5": "支持韩语、英语、中文、日语、越南语。更多语言即将上线！"}, "shareIdea": {"title": "💡 分享您的想法", "ideaTitle": "标题", "ideaTitlePlaceholder": "用一句话描述您的想法", "featureArea": "功能领域", "featureAreaPlaceholder": "请选择...", "description": "描述", "descriptionPlaceholder": "请详细描述您的想法...", "photo": "图片（可选）", "uploadImage": "📷 上传图片", "submitBtn": "提交想法", "submitting": "提交中...", "fillRequired": "请填写所有必填项。", "submitFailed": "提交失败，请重试。", "successTitle": "感谢您的想法！", "successDesc": "我们会尽快审核。", "featureOptions": {"community": "社区", "service": "服务", "other": "其他"}}, "needHelp": {"title": "🤝 需要更多帮助？", "ideaTitle": "标题", "ideaTitlePlaceholder": "简要描述您的问题", "details": "详细内容", "detailsPlaceholder": "请描述您需要帮助的内容...", "contact": "邮箱 / 联系方式（可选）", "contactPlaceholder": "我们如何联系您？", "photo": "图片（可选）", "uploadImage": "📷 上传图片", "sendBtn": "发送请求", "sending": "发送中...", "fillRequired": "请填写所有必填项。", "sendFailed": "发送失败，请重试。", "successTitle": "您的请求已发送！", "successDesc": "我们的团队将尽快回复您。", "topics": {"visa": "签证 / 居留", "housing": "住房", "job": "就业 / 工作", "school": "学校 / 教育", "health": "健康 / 医院", "other": "其他"}}},
  "signup": {"title": "注册", "email": "邮箱", "password": "密码", "nickname": "昵称", "country": "国家", "preferredLanguage": "偏好语言", "purpose": "目的", "status": "当前状态", "check": "确认", "signingUp": "注册中...", "cancel": "取消", "emailRequired": "请确认邮箱是否可用。", "nicknameRequired": "请确认昵称是否可用。", "passwordRequired": "请输入密码。", "failed": "注册失败，请重试。", "success": "注册成功。", "emailCheckFailed": "邮箱确认失败，请重试。", "nicknameCheckFailed": "昵称确认失败，请重试。", "enterEmail": "请输入邮箱。", "enterNickname": "请输入昵称。", "confirmLanguageTitle": "确认语言选择", "confirm": "确认", "purposeOptions": {"community": "社区", "service": "服务", "information": "信息"}, "statusOptions": {"living": "目前居住在韩国", "planning": "计划移居韩国"}},
  "findId": {"title": "找回账号", "desc": "请输入注册时使用的昵称。", "nicknamePlaceholder": "昵称", "find": "查找", "searching": "搜索中...", "close": "关闭", "enterNickname": "请输入昵称。", "notFound": "找不到该昵称，请确认后重试。", "failed": "找回账号失败，请重试。", "yourEmail": "您的邮箱"},
  "resetPassword": {"title": "重置密码", "step1Desc": "请输入与您账号关联的邮箱。", "codeSentTo": "验证码已发送至", "step2Desc": "请输入发送到您邮箱的验证码。", "step3Desc": "请输入新密码。", "newPassword": "新密码", "confirmPassword": "确认密码", "sendCode": "发送验证码", "sending": "发送中...", "back": "返回", "verify": "验证", "verifying": "验证中...", "resetBtn": "重置密码", "resetting": "重置中...", "successTitle": "密码重置成功", "successDesc": "您的密码已成功重置，请使用新密码登录。", "enterEmail": "请输入邮箱。", "enterCode": "请输入验证码。", "codeLength": "验证码必须是8位数字。", "codeExpired": "验证码已过期，请重新申请。", "codeInvalid": "验证码无效，请重新确认。", "sendFailed": "发送验证码失败，请重试。", "verifyFailed": "验证失败，请重试。", "enterNewPassword": "请输入新密码。", "passwordMismatch": "两次密码不一致。", "resetFailed": "密码重置失败，请重试。"},
  "writePost": {"title": "写帖子", "category": "分类", "categoryPlaceholder": "选择分类", "postTitle": "标题", "titlePlaceholder": "请输入标题", "content": "内容", "contentPlaceholder": "请写下您的帖子...", "photo": "图片（可选）", "uploadImage": "📷 上传图片", "submit": "提交", "saving": "保存中...", "fillRequired": "请填写所有必填项。", "failed": "保存帖子失败。"},
  "languages": {"en": "英语", "ko": "韩语", "zh": "中文", "ja": "日语", "es": "西班牙语", "vi": "越南语"}
}

# ──────────────────────────────────────────────────────────
# JAPANESE
# ──────────────────────────────────────────────────────────
JA = {
  "nav": {"main": "メイン", "community": "コミュニティ", "services": "サービス", "help": "ヘルプ", "myPage": "マイページ"},
  "common": {"loading": "読み込み中...", "save": "保存", "cancel": "キャンセル", "delete": "削除", "edit": "編集", "close": "閉じる", "send": "送信", "submit": "提出", "confirm": "確認", "back": "戻る", "search": "検索", "language": "言語", "check": "確認", "verify": "認証", "by": "投稿者", "justNow": "たった今", "minutesAgo": "{{count}}分前", "hoursAgo": "{{count}}時間前", "daysAgo": "{{count}}日前", "unknown": "不明", "exploreCommunity": "コミュニティへ →"},
  "auth": {"login": "ログイン", "logout": "ログアウト", "signUp": "サインアップ", "loginRequired": "ログインが必要です", "loginRequiredDesc": "このページを表示するにはログインが必要です。", "loggingIn": "ログイン中...", "loginSuccess": "ログイン成功！", "email": "メールアドレス", "password": "パスワード", "enterEmail": "メールアドレスを入力してください", "enterPassword": "パスワードを入力してください", "emailRequired": "メールアドレスを入力してください。", "passwordRequired": "パスワードを入力してください。", "loginFailed": "ログインに失敗しました。もう一度お試しください。", "findId": "IDを探す", "resetPasswordLink": "パスワードをリセット"},
  "community": {"title": "コミュニティ", "writePost": "投稿を書く", "comments": "コメント", "noComments": "まだコメントがありません。", "commentPlaceholder": "コメントを入力...", "loginToComment": "コメントするにはログインが必要です。", "picture": "画像", "noPostsYet": "投稿がありません。", "postNotFound": "投稿が見つかりません", "report": "報告", "blockUser": "ユーザーをブロック", "unblockUser": "ブロック解除", "youAreBlocked": "このユーザーをブロックしています", "edit": "編集", "delete": "削除", "editPost": "投稿を編集", "deleteConfirm": "本当に削除しますか？", "saving": "保存中...", "userProfile": "ユーザープロフィール", "userNotFound": "ユーザーが見つかりません。", "posts": "投稿", "noPostsAvailable": "投稿がありません。", "failedToLoad": "投稿の読み込みに失敗しました", "removeImage": "× 削除", "blockAlready": "このユーザーはすでにブロックされています。", "blockFailed": "ブロックに失敗しました。もう一度お試しください。", "blockSuccess": "ユーザーをブロックしました。", "unblockFailed": "ブロック解除に失敗しました。もう一度お試しください。", "unblockSuccess": "ブロックを解除しました。", "categories": {"all": "すべての投稿", "food": "食べ物 🍚", "housing": "住居 🏠", "school": "学校 🏫", "job": "仕事 👨‍💻", "hospital": "病院 🏥", "info": "情報 💁", "free": "自由 🍀"}},
  "home": {"recentPosts": "最新投稿", "trendingPosts": "人気投稿", "noRecentPosts": "まだ最新投稿がありません。", "noTrendingPosts": "現在人気投稿はありません。", "banners": {"policy": {"title": "外国人支援政策", "desc": "2024年新政策・支援情報"}, "visa": {"title": "ビザ・在留アップデート", "desc": "最新ビザ規定と変更点"}, "services": {"title": "外国人向けサービス", "desc": "ANNYEONGの全サービスを見る"}, "announcements": {"title": "ANNYEONGのお知らせ", "desc": "コミュニティの更新と新機能"}}},
  "myPage": {"title": "マイプロフィール", "myPosts": "マイ投稿", "likedPosts": "いいねした投稿", "friends": "フレンド", "settings": "設定", "myPostsDesc": "あなたが投稿した記事", "likedPostsDesc": "いいねした投稿", "friendsDesc": "フレンドとブロックユーザー", "settingsDesc": "プロフィール、パスワード、言語", "signInPrompt": "プロフィールを表示するにはログインしてください", "noPosts": "投稿がありません。", "noLikedPosts": "いいねした投稿がありません。", "noPostsWritten": "まだ投稿がありません。", "noPostsLiked": "まだいいねした投稿がありません。"},
  "settings": {"title": "設定", "editProfile": "プロフィール編集", "editProfileDesc": "ニックネーム、国旗、プロフィール写真", "editProfileTitle": "プロフィール編集", "resetPassword": "パスワードリセット", "resetPasswordDesc": "パスワードを更新する", "resetPasswordTitle": "パスワードリセット", "chooseLanguage": "言語を選択", "chooseLanguageDesc": "お好みの言語を選択してください", "chooseLanguageHint": "コンテンツの翻訳と設定に使用する言語を選択してください。", "confirmSelection": "選択を確定", "languageUpdated": "言語が更新されました！", "saving": "保存中...", "profilePhoto": "プロフィール写真", "choosePhoto": "📷 写真を選ぶ", "nickname": "ニックネーム", "nicknamePlaceholder": "ニックネームを入力してください", "nicknameEmpty": "ニックネームは必須です。", "imageUploadFailed": "画像のアップロードに失敗しました。もう一度お試しください。", "saveFailed": "保存に失敗しました。もう一度お試しください。", "savedSuccess": "保存しました！", "saveChanges": "変更を保存", "currentPassword": "現在のパスワード", "currentPasswordPlaceholder": "現在のパスワードを入力してください", "newPassword": "新しいパスワード", "newPasswordPlaceholder": "6文字以上", "confirmNewPassword": "新しいパスワードの確認", "confirmNewPasswordPlaceholder": "新しいパスワードを再入力してください", "verifyBtn": "認証", "verifying": "認証中...", "verified": "✓ パスワード確認済み", "incorrectPassword": "現在のパスワードが正しくありません。", "passwordRequired": "現在のパスワードを入力してください。", "enterNewPasswordBelow": "新しいパスワードを入力してください。", "passwordMismatch": "パスワードが一致しません。", "updatePassword": "パスワードを更新", "updating": "更新中...", "passwordUpdated": "パスワードが正常に更新されました！"},
  "friends": {"title": "フレンド", "friendsTab": "フレンド", "blockedTab": "ブロックユーザー", "friendsComingSoon": "フレンド機能は準備中です。", "noBlocked": "ブロックしているユーザーはいません。", "unblock": "ブロック解除", "unblocking": "処理中...", "loginToView": "フレンドとブロック一覧を見るにはログインしてください。"},
  "report": {"title": "報告", "reason": "報告理由", "reasonPlaceholder": "理由を選択してください", "description": "詳細（任意）", "descriptionPlaceholder": "詳細を入力してください...", "attachImage": "📷 画像を添付", "removeImage": "× 削除", "submit": "報告を送信", "submitting": "送信中...", "cancel": "キャンセル", "successTitle": "報告が受け付けられました。", "successDesc": "確認後、対応いたします。", "duplicatePost": "この投稿はすでに報告済みです。", "duplicateComment": "このコメントはすでに報告済みです。", "errorGeneric": "エラーが発生しました。もう一度お試しください。", "selectReason": "報告理由を選択してください。", "reasons": {"hate": "ヘイト / 不快な言語", "sexual": "性的ハラスメント", "spam": "スパム / 広告", "scam": "詐欺 / 不審な活動", "misinformation": "虚偽情報", "privacy": "プライバシー侵害", "illegal": "違法 / 危険なコンテンツ", "other": "その他"}},
  "help": {"title": "ヘルプ & サポート", "faqTitle": "よくある質問", "shareIdeasTitle": "アイデアをシェア", "shareIdeasDesc": "機能やサービスのアイデアがありますか？教えてください！良いアイデアは実装され、採用されたアイデアには報酬があります。", "shareIdeasBtn": "アイデアをシェア", "needHelpTitle": "もっとサポートが必要ですか？", "needHelpDesc": "お探しのものが見つかりませんか？いつでもチームにお問い合わせください。", "contactBtn": "チームに問い合わせ", "faqs": {"q1": "ANNYEONGは本当に無料ですか？", "a1": "コミュニティのアクセスと基本情報は完全に無料です。一部のプレミアムサービスは有料の場合がありますが、初回相談は常に無料です。", "q2": "サポートを受けるまでどのくらいかかりますか？", "a2": "ほとんどの問い合わせに1〜2時間以内に返答します。緊急の場合は優先的に対応します。", "q3": "ビザに必要な書類は何ですか？", "a3": "ビザの種類によって異なります。コミュニティに参加するかお問い合わせいただければ個別にご案内します。", "q4": "韓国に来る前にANNYEONGを使えますか？", "a4": "もちろんです！本プラットフォームは来韓前の準備のためにも活用できます。", "q5": "どの言語に対応していますか？", "a5": "韓国語、英語、中国語、日本語、ベトナム語に対応しています。その他の言語も近日追加予定！"}, "shareIdea": {"title": "💡 アイデアをシェア", "ideaTitle": "タイトル", "ideaTitlePlaceholder": "アイデアを一言で", "featureArea": "機能エリア", "featureAreaPlaceholder": "選択...", "description": "説明", "descriptionPlaceholder": "アイデアの詳細を入力してください...", "photo": "写真（任意）", "uploadImage": "📷 画像をアップロード", "submitBtn": "アイデアを送信", "submitting": "送信中...", "fillRequired": "すべての必須項目を入力してください。", "submitFailed": "送信に失敗しました。もう一度お試しください。", "successTitle": "アイデアをありがとうございます！", "successDesc": "すぐに確認します。", "featureOptions": {"community": "コミュニティ", "service": "サービス", "other": "その他"}}, "needHelp": {"title": "🤝 もっとサポートが必要ですか？", "ideaTitle": "タイトル", "ideaTitlePlaceholder": "問題を簡単に要約してください", "details": "詳細", "detailsPlaceholder": "サポートが必要な内容を詳しく入力してください...", "contact": "メール / 連絡先（任意）", "contactPlaceholder": "連絡先を教えてください", "photo": "写真（任意）", "uploadImage": "📷 画像をアップロード", "sendBtn": "リクエストを送信", "sending": "送信中...", "fillRequired": "すべての必須項目を入力してください。", "sendFailed": "送信に失敗しました。もう一度お試しください。", "successTitle": "リクエストが送信されました！", "successDesc": "チームがすぐにご連絡します。", "topics": {"visa": "ビザ / 在留", "housing": "住居", "job": "就職 / 業務", "school": "学校 / 教育", "health": "健康 / 病院", "other": "その他"}}},
  "signup": {"title": "サインアップ", "email": "メールアドレス", "password": "パスワード", "nickname": "ニックネーム", "country": "国", "preferredLanguage": "使用言語", "purpose": "目的", "status": "現在の状況", "check": "確認", "signingUp": "登録中...", "cancel": "キャンセル", "emailRequired": "メールアドレスが使用可能か確認してください。", "nicknameRequired": "ニックネームが使用可能か確認してください。", "passwordRequired": "パスワードを入力してください。", "failed": "登録に失敗しました。もう一度お試しください。", "success": "登録が完了しました。", "emailCheckFailed": "メールアドレスの確認に失敗しました。もう一度お試しください。", "nicknameCheckFailed": "ニックネームの確認に失敗しました。もう一度お試しください。", "enterEmail": "メールアドレスを入力してください。", "enterNickname": "ニックネームを入力してください。", "confirmLanguageTitle": "言語選択の確認", "confirm": "確認", "purposeOptions": {"community": "コミュニティ", "service": "サービス", "information": "情報"}, "statusOptions": {"living": "現在韓国在住", "planning": "韓国移住予定"}},
  "findId": {"title": "IDを探す", "desc": "登録時に使用したニックネームを入力してください。", "nicknamePlaceholder": "ニックネーム", "find": "探す", "searching": "検索中...", "close": "閉じる", "enterNickname": "ニックネームを入力してください。", "notFound": "ニックネームが見つかりません。ご確認の上、もう一度お試しください。", "failed": "ID検索に失敗しました。もう一度お試しください。", "yourEmail": "登録メールアドレス"},
  "resetPassword": {"title": "パスワードをリセット", "step1Desc": "アカウントに登録されたメールアドレスを入力してください。", "codeSentTo": "認証コードを送信しました:", "step2Desc": "メールに届いた認証コードを入力してください。", "step3Desc": "新しいパスワードを入力してください。", "newPassword": "新しいパスワード", "confirmPassword": "パスワードの確認", "sendCode": "認証コードを送信", "sending": "送信中...", "back": "戻る", "verify": "認証", "verifying": "認証中...", "resetBtn": "パスワードをリセット", "resetting": "リセット中...", "successTitle": "パスワードのリセットが完了しました", "successDesc": "パスワードが正常にリセットされました。新しいパスワードでログインしてください。", "enterEmail": "メールアドレスを入力してください。", "enterCode": "認証コードを入力してください。", "codeLength": "認証コードは8桁である必要があります。", "codeExpired": "認証コードの有効期限が切れました。新しいコードを申請してください。", "codeInvalid": "認証コードが無効です。もう一度確認してください。", "sendFailed": "認証コードの送信に失敗しました。もう一度お試しください。", "verifyFailed": "認証に失敗しました。もう一度お試しください。", "enterNewPassword": "新しいパスワードを入力してください。", "passwordMismatch": "パスワードが一致しません。", "resetFailed": "パスワードのリセットに失敗しました。もう一度お試しください。"},
  "writePost": {"title": "投稿を書く", "category": "カテゴリ", "categoryPlaceholder": "カテゴリを選択", "postTitle": "タイトル", "titlePlaceholder": "タイトルを入力してください", "content": "内容", "contentPlaceholder": "投稿内容を入力してください...", "photo": "写真（任意）", "uploadImage": "📷 画像をアップロード", "submit": "送信", "saving": "保存中...", "fillRequired": "すべての必須項目を入力してください。", "failed": "投稿の保存に失敗しました。"},
  "languages": {"en": "英語", "ko": "韓国語", "zh": "中国語", "ja": "日本語", "es": "スペイン語", "vi": "ベトナム語"}
}

# ──────────────────────────────────────────────────────────
# SPANISH
# ──────────────────────────────────────────────────────────
ES = {
  "nav": {"main": "Principal", "community": "Comunidad", "services": "Servicios", "help": "Ayuda", "myPage": "Mi Página"},
  "common": {"loading": "Cargando...", "save": "Guardar", "cancel": "Cancelar", "delete": "Eliminar", "edit": "Editar", "close": "Cerrar", "send": "Enviar", "submit": "Enviar", "confirm": "Confirmar", "back": "Volver", "search": "Buscar", "language": "Idioma", "check": "Verificar", "verify": "Verificar", "by": "por", "justNow": "ahora mismo", "minutesAgo": "hace {{count}}m", "hoursAgo": "hace {{count}}h", "daysAgo": "hace {{count}}d", "unknown": "Desconocido", "exploreCommunity": "Ir a Comunidad →"},
  "auth": {"login": "Iniciar sesión", "logout": "Cerrar sesión", "signUp": "Registrarse", "loginRequired": "Inicio de sesión requerido", "loginRequiredDesc": "Debes iniciar sesión para ver esta página.", "loggingIn": "Iniciando sesión...", "loginSuccess": "¡Inicio de sesión exitoso!", "email": "Correo electrónico", "password": "Contraseña", "enterEmail": "Ingresa tu correo electrónico", "enterPassword": "Ingresa tu contraseña", "emailRequired": "Por favor ingresa tu correo electrónico.", "passwordRequired": "Por favor ingresa tu contraseña.", "loginFailed": "Error al iniciar sesión. Inténtalo de nuevo.", "findId": "Encontrar ID", "resetPasswordLink": "Restablecer contraseña"},
  "community": {"title": "Comunidad", "writePost": "Escribir publicación", "comments": "Comentarios", "noComments": "Aún no hay comentarios.", "commentPlaceholder": "Escribe un comentario...", "loginToComment": "Inicia sesión para comentar.", "picture": "Imagen", "noPostsYet": "Aún no hay publicaciones.", "postNotFound": "Publicación no encontrada", "report": "Reportar", "blockUser": "Bloquear usuario", "unblockUser": "Desbloquear usuario", "youAreBlocked": "Has bloqueado a este usuario", "edit": "Editar", "delete": "Eliminar", "editPost": "Editar publicación", "deleteConfirm": "¿Seguro que deseas eliminar?", "saving": "Guardando...", "userProfile": "Perfil de usuario", "userNotFound": "Usuario no encontrado.", "posts": "Publicaciones", "noPostsAvailable": "No hay publicaciones disponibles.", "failedToLoad": "Error al cargar publicaciones", "removeImage": "× Eliminar", "blockAlready": "Este usuario ya está bloqueado.", "blockFailed": "Error al bloquear. Inténtalo de nuevo.", "blockSuccess": "Usuario bloqueado.", "unblockFailed": "Error al desbloquear. Inténtalo de nuevo.", "unblockSuccess": "Desbloqueado con éxito.", "categories": {"all": "Todas las publicaciones", "food": "Comida 🍚", "housing": "Vivienda 🏠", "school": "Escuela 🏫", "job": "Trabajo 👨‍💻", "hospital": "Hospital 🏥", "info": "Info 💁", "free": "Libre 🍀"}},
  "home": {"recentPosts": "Publicaciones recientes", "trendingPosts": "Publicaciones populares", "noRecentPosts": "Aún no hay publicaciones recientes.", "noTrendingPosts": "No hay publicaciones populares ahora.", "banners": {"policy": {"title": "Políticas de apoyo para extranjeros", "desc": "Nuevas políticas y financiación 2024"}, "visa": {"title": "Actualizaciones de visado y residencia", "desc": "Últimas regulaciones y cambios"}, "services": {"title": "Servicios para extranjeros", "desc": "Descubre todos los servicios de ANNYEONG"}, "announcements": {"title": "Anuncios de ANNYEONG", "desc": "Actualizaciones y nuevas funciones"}}},
  "myPage": {"title": "Mi Perfil", "myPosts": "Mis Publicaciones", "likedPosts": "Me gustas", "friends": "Amigos", "settings": "Configuración", "myPostsDesc": "Publicaciones que has publicado", "likedPostsDesc": "Publicaciones que te gustaron", "friendsDesc": "Amigos y usuarios bloqueados", "settingsDesc": "Perfil, contraseña, idioma", "signInPrompt": "Inicia sesión para ver tu perfil", "noPosts": "Aún no hay publicaciones.", "noLikedPosts": "Aún no hay publicaciones con me gusta.", "noPostsWritten": "Aún no has escrito ninguna publicación.", "noPostsLiked": "Aún no has dado me gusta a ninguna publicación."},
  "settings": {"title": "Configuración", "editProfile": "Editar Perfil", "editProfileDesc": "Apodo, bandera y foto de perfil", "editProfileTitle": "Editar Perfil", "resetPassword": "Restablecer Contraseña", "resetPasswordDesc": "Actualiza tu contraseña", "resetPasswordTitle": "Restablecer Contraseña", "chooseLanguage": "Elegir Idioma", "chooseLanguageDesc": "Elige tu idioma preferido", "chooseLanguageHint": "Elige el idioma para la traducción de contenido y preferencias.", "confirmSelection": "Confirmar Selección", "languageUpdated": "¡Idioma actualizado!", "saving": "Guardando...", "profilePhoto": "Foto de perfil", "choosePhoto": "📷 Elegir foto", "nickname": "Apodo", "nicknamePlaceholder": "Tu apodo", "nicknameEmpty": "El apodo no puede estar vacío.", "imageUploadFailed": "Error al subir la imagen. Inténtalo de nuevo.", "saveFailed": "Error al guardar. Inténtalo de nuevo.", "savedSuccess": "¡Guardado exitosamente!", "saveChanges": "Guardar cambios", "currentPassword": "Contraseña actual", "currentPasswordPlaceholder": "Ingresa tu contraseña actual", "newPassword": "Nueva contraseña", "newPasswordPlaceholder": "Al menos 6 caracteres", "confirmNewPassword": "Confirmar nueva contraseña", "confirmNewPasswordPlaceholder": "Reingresa la nueva contraseña", "verifyBtn": "Verificar", "verifying": "Verificando...", "verified": "✓ Contraseña verificada", "incorrectPassword": "La contraseña actual es incorrecta.", "passwordRequired": "Por favor ingresa tu contraseña actual.", "enterNewPasswordBelow": "Ingresa tu nueva contraseña a continuación.", "passwordMismatch": "Las contraseñas no coinciden.", "updatePassword": "Actualizar contraseña", "updating": "Actualizando...", "passwordUpdated": "¡Contraseña actualizada exitosamente!"},
  "friends": {"title": "Amigos", "friendsTab": "Amigos", "blockedTab": "Usuarios bloqueados", "friendsComingSoon": "La función de amigos estará disponible pronto.", "noBlocked": "No hay usuarios bloqueados.", "unblock": "Desbloquear", "unblocking": "Procesando...", "loginToView": "Inicia sesión para ver tus amigos y usuarios bloqueados."},
  "report": {"title": "Reportar", "reason": "Motivo", "reasonPlaceholder": "Selecciona un motivo", "description": "Detalles (opcional)", "descriptionPlaceholder": "Describe el problema en detalle...", "attachImage": "📷 Adjuntar imagen", "removeImage": "× Eliminar", "submit": "Enviar reporte", "submitting": "Enviando...", "cancel": "Cancelar", "successTitle": "Reporte enviado.", "successDesc": "Revisaremos y tomaremos medidas.", "duplicatePost": "Ya has reportado esta publicación.", "duplicateComment": "Ya has reportado este comentario.", "errorGeneric": "Ocurrió un error. Inténtalo de nuevo.", "selectReason": "Por favor selecciona un motivo.", "reasons": {"hate": "Odio / Lenguaje ofensivo", "sexual": "Acoso sexual", "spam": "Spam / Publicidad", "scam": "Fraude / Actividad sospechosa", "misinformation": "Desinformación", "privacy": "Violación de privacidad", "illegal": "Contenido ilegal / peligroso", "other": "Otro"}},
  "help": {"title": "Ayuda & Soporte", "faqTitle": "Preguntas frecuentes", "shareIdeasTitle": "Comparte tus ideas", "shareIdeasDesc": "¿Tienes una idea de función o servicio? ¡Cuéntanos! Las buenas ideas se implementan y las sugerencias adoptadas reciben recompensas.", "shareIdeasBtn": "Compartir idea", "needHelpTitle": "¿Necesitas más ayuda?", "needHelpDesc": "¿No encuentras lo que buscas? Contacta a nuestro equipo en cualquier momento.", "contactBtn": "Contactar al equipo", "faqs": {"q1": "¿ANNYEONG es realmente gratis?", "a1": "El acceso a la comunidad e información básica es completamente gratuito. Algunos servicios premium pueden tener costos, pero la consulta inicial siempre es gratuita.", "q2": "¿Cuánto tiempo tarda en recibir ayuda?", "a2": "Respondemos la mayoría de consultas en 1-2 horas. Para casos urgentes, priorizamos respuestas más rápidas.", "q3": "¿Qué documentos necesito para una visa?", "a3": "Depende de tu tipo de visa. Ofrecemos orientación personalizada, únete a la comunidad o contáctanos.", "q4": "¿Puedo usar ANNYEONG antes de llegar a Corea?", "a4": "¡Por supuesto! Nuestra plataforma ayuda a prepararse antes de llegar.", "q5": "¿Qué idiomas se admiten?", "a5": "Admitimos coreano, inglés, chino, japonés, vietnamita. ¡Más idiomas próximamente!"}, "shareIdea": {"title": "💡 Comparte tu idea", "ideaTitle": "Título", "ideaTitlePlaceholder": "Tu idea en una línea", "featureArea": "Área de función", "featureAreaPlaceholder": "Seleccionar...", "description": "Descripción", "descriptionPlaceholder": "Describe tu idea en detalle...", "photo": "Foto (opcional)", "uploadImage": "📷 Subir imagen", "submitBtn": "Enviar idea", "submitting": "Enviando...", "fillRequired": "Por favor completa todos los campos requeridos.", "submitFailed": "Error al enviar. Inténtalo de nuevo.", "successTitle": "¡Gracias por tu idea!", "successDesc": "La revisaremos pronto.", "featureOptions": {"community": "Comunidad", "service": "Servicio", "other": "Otro"}}, "needHelp": {"title": "🤝 ¿Necesitas más ayuda?", "ideaTitle": "Título", "ideaTitlePlaceholder": "Resumen breve de tu problema", "details": "Detalles", "detailsPlaceholder": "Describe en qué necesitas ayuda...", "contact": "Correo / Contacto (opcional)", "contactPlaceholder": "¿Cómo podemos contactarte?", "photo": "Foto (opcional)", "uploadImage": "📷 Subir imagen", "sendBtn": "Enviar solicitud", "sending": "Enviando...", "fillRequired": "Por favor completa todos los campos requeridos.", "sendFailed": "Error al enviar. Inténtalo de nuevo.", "successTitle": "¡Tu solicitud fue enviada!", "successDesc": "Nuestro equipo te responderá pronto.", "topics": {"visa": "Visa / Residencia", "housing": "Vivienda", "job": "Trabajo / Empleo", "school": "Escuela / Educación", "health": "Salud / Hospital", "other": "Otro"}}},
  "signup": {"title": "Registrarse", "email": "Correo electrónico", "password": "Contraseña", "nickname": "Apodo", "country": "País", "preferredLanguage": "Idioma preferido", "purpose": "Propósito", "status": "Estado actual", "check": "Verificar", "signingUp": "Registrando...", "cancel": "Cancelar", "emailRequired": "Verifica que tu correo esté disponible.", "nicknameRequired": "Verifica que tu apodo esté disponible.", "passwordRequired": "Por favor ingresa una contraseña.", "failed": "Error al registrarse. Inténtalo de nuevo.", "success": "Registro completado exitosamente.", "emailCheckFailed": "Error al verificar el correo. Inténtalo de nuevo.", "nicknameCheckFailed": "Error al verificar el apodo. Inténtalo de nuevo.", "enterEmail": "Por favor ingresa un correo.", "enterNickname": "Por favor ingresa un apodo.", "confirmLanguageTitle": "Confirmar selección de idioma", "confirm": "Confirmar", "purposeOptions": {"community": "Comunidad", "service": "Servicio", "information": "Información"}, "statusOptions": {"living": "Actualmente viviendo en Corea", "planning": "Planeando mudarse a Corea"}},
  "findId": {"title": "Encontrar ID", "desc": "Por favor ingresa el apodo que usaste al registrarte.", "nicknamePlaceholder": "Tu apodo", "find": "Buscar", "searching": "Buscando...", "close": "Cerrar", "enterNickname": "Por favor ingresa tu apodo.", "notFound": "Apodo no encontrado. Por favor verifica e inténtalo de nuevo.", "failed": "Error al buscar ID. Inténtalo de nuevo.", "yourEmail": "Tu correo electrónico"},
  "resetPassword": {"title": "Restablecer contraseña", "step1Desc": "Ingresa el correo asociado a tu cuenta.", "codeSentTo": "Código de verificación enviado a", "step2Desc": "Ingresa el código de verificación enviado a tu correo.", "step3Desc": "Ingresa tu nueva contraseña.", "newPassword": "Nueva contraseña", "confirmPassword": "Confirmar contraseña", "sendCode": "Enviar código de verificación", "sending": "Enviando...", "back": "Volver", "verify": "Verificar", "verifying": "Verificando...", "resetBtn": "Restablecer contraseña", "resetting": "Restableciendo...", "successTitle": "Contraseña restablecida exitosamente", "successDesc": "Tu contraseña ha sido restablecida. Por favor inicia sesión con tu nueva contraseña.", "enterEmail": "Por favor ingresa tu correo.", "enterCode": "Por favor ingresa el código de verificación.", "codeLength": "El código debe tener 8 dígitos.", "codeExpired": "El código expiró. Solicita uno nuevo.", "codeInvalid": "Código inválido. Verifica e inténtalo de nuevo.", "sendFailed": "Error al enviar el código. Inténtalo de nuevo.", "verifyFailed": "Error de verificación. Inténtalo de nuevo.", "enterNewPassword": "Por favor ingresa una nueva contraseña.", "passwordMismatch": "Las contraseñas no coinciden.", "resetFailed": "Error al restablecer contraseña. Inténtalo de nuevo."},
  "writePost": {"title": "Escribir publicación", "category": "Categoría", "categoryPlaceholder": "Selecciona una categoría", "postTitle": "Título", "titlePlaceholder": "Ingresa un título", "content": "Contenido", "contentPlaceholder": "Escribe tu publicación...", "photo": "Foto (opcional)", "uploadImage": "📷 Subir imagen", "submit": "Enviar", "saving": "Guardando...", "fillRequired": "Por favor completa todos los campos requeridos.", "failed": "Error al guardar la publicación."},
  "languages": {"en": "Inglés", "ko": "Coreano", "zh": "Chino", "ja": "Japonés", "es": "Español", "vi": "Vietnamita"}
}

# ──────────────────────────────────────────────────────────
# VIETNAMESE
# ──────────────────────────────────────────────────────────
VI = {
  "nav": {"main": "Trang chính", "community": "Cộng đồng", "services": "Dịch vụ", "help": "Trợ giúp", "myPage": "Trang của tôi"},
  "common": {"loading": "Đang tải...", "save": "Lưu", "cancel": "Hủy", "delete": "Xóa", "edit": "Sửa", "close": "Đóng", "send": "Gửi", "submit": "Gửi", "confirm": "Xác nhận", "back": "Quay lại", "search": "Tìm kiếm", "language": "Ngôn ngữ", "check": "Kiểm tra", "verify": "Xác thực", "by": "bởi", "justNow": "vừa xong", "minutesAgo": "{{count}} phút trước", "hoursAgo": "{{count}} giờ trước", "daysAgo": "{{count}} ngày trước", "unknown": "Không rõ", "exploreCommunity": "Đến Cộng đồng →"},
  "auth": {"login": "Đăng nhập", "logout": "Đăng xuất", "signUp": "Đăng ký", "loginRequired": "Yêu cầu đăng nhập", "loginRequiredDesc": "Bạn cần đăng nhập để xem trang này.", "loggingIn": "Đang đăng nhập...", "loginSuccess": "Đăng nhập thành công!", "email": "Email", "password": "Mật khẩu", "enterEmail": "Nhập email của bạn", "enterPassword": "Nhập mật khẩu", "emailRequired": "Vui lòng nhập email.", "passwordRequired": "Vui lòng nhập mật khẩu.", "loginFailed": "Đăng nhập thất bại. Vui lòng thử lại.", "findId": "Tìm tài khoản", "resetPasswordLink": "Đặt lại mật khẩu"},
  "community": {"title": "Cộng đồng", "writePost": "Viết bài", "comments": "Bình luận", "noComments": "Chưa có bình luận nào.", "commentPlaceholder": "Viết bình luận...", "loginToComment": "Đăng nhập để bình luận.", "picture": "Hình ảnh", "noPostsYet": "Chưa có bài viết nào.", "postNotFound": "Không tìm thấy bài viết", "report": "Báo cáo", "blockUser": "Chặn người dùng", "unblockUser": "Bỏ chặn", "youAreBlocked": "Bạn đã chặn người dùng này", "edit": "Sửa", "delete": "Xóa", "editPost": "Sửa bài viết", "deleteConfirm": "Bạn có chắc chắn muốn xóa không?", "saving": "Đang lưu...", "userProfile": "Hồ sơ người dùng", "userNotFound": "Không tìm thấy người dùng.", "posts": "Bài viết", "noPostsAvailable": "Không có bài viết nào.", "failedToLoad": "Không thể tải bài viết", "removeImage": "× Xóa", "blockAlready": "Bạn đã chặn người dùng này rồi.", "blockFailed": "Chặn thất bại. Vui lòng thử lại.", "blockSuccess": "Đã chặn người dùng.", "unblockFailed": "Bỏ chặn thất bại. Vui lòng thử lại.", "unblockSuccess": "Đã bỏ chặn thành công.", "categories": {"all": "Tất cả bài viết", "food": "Ẩm thực 🍚", "housing": "Nhà ở 🏠", "school": "Trường học 🏫", "job": "Việc làm 👨‍💻", "hospital": "Bệnh viện 🏥", "info": "Thông tin 💁", "free": "Tự do 🍀"}},
  "home": {"recentPosts": "Bài viết mới nhất", "trendingPosts": "Bài viết thịnh hành", "noRecentPosts": "Chưa có bài viết mới.", "noTrendingPosts": "Hiện không có bài viết thịnh hành.", "banners": {"policy": {"title": "Chính sách hỗ trợ người nước ngoài", "desc": "Chính sách và thông tin tài trợ mới 2024"}, "visa": {"title": "Cập nhật visa và cư trú", "desc": "Quy định visa mới nhất và thay đổi"}, "services": {"title": "Dịch vụ cho người quốc tế", "desc": "Khám phá tất cả dịch vụ ANNYEONG"}, "announcements": {"title": "Thông báo ANNYEONG", "desc": "Cập nhật cộng đồng và tính năng mới"}}},
  "myPage": {"title": "Hồ sơ của tôi", "myPosts": "Bài viết của tôi", "likedPosts": "Bài viết đã thích", "friends": "Bạn bè", "settings": "Cài đặt", "myPostsDesc": "Các bài bạn đã đăng", "likedPostsDesc": "Các bài bạn đã thích", "friendsDesc": "Bạn bè & người dùng bị chặn", "settingsDesc": "Hồ sơ, mật khẩu, ngôn ngữ", "signInPrompt": "Đăng nhập để xem hồ sơ của bạn", "noPosts": "Chưa có bài viết nào.", "noLikedPosts": "Chưa có bài viết nào được thích.", "noPostsWritten": "Bạn chưa viết bài viết nào.", "noPostsLiked": "Bạn chưa thích bài viết nào."},
  "settings": {"title": "Cài đặt", "editProfile": "Chỉnh sửa hồ sơ", "editProfileDesc": "Biệt danh, cờ và ảnh hồ sơ", "editProfileTitle": "Chỉnh sửa hồ sơ", "resetPassword": "Đặt lại mật khẩu", "resetPasswordDesc": "Cập nhật mật khẩu của bạn", "resetPasswordTitle": "Đặt lại mật khẩu", "chooseLanguage": "Chọn ngôn ngữ", "chooseLanguageDesc": "Chọn ngôn ngữ ưa thích của bạn", "chooseLanguageHint": "Chọn ngôn ngữ dùng cho dịch nội dung và cài đặt.", "confirmSelection": "Xác nhận lựa chọn", "languageUpdated": "Ngôn ngữ đã được cập nhật!", "saving": "Đang lưu...", "profilePhoto": "Ảnh hồ sơ", "choosePhoto": "📷 Chọn ảnh", "nickname": "Biệt danh", "nicknamePlaceholder": "Biệt danh của bạn", "nicknameEmpty": "Biệt danh không được để trống.", "imageUploadFailed": "Tải ảnh thất bại. Vui lòng thử lại.", "saveFailed": "Lưu thất bại. Vui lòng thử lại.", "savedSuccess": "Đã lưu thành công!", "saveChanges": "Lưu thay đổi", "currentPassword": "Mật khẩu hiện tại", "currentPasswordPlaceholder": "Nhập mật khẩu hiện tại", "newPassword": "Mật khẩu mới", "newPasswordPlaceholder": "Ít nhất 6 ký tự", "confirmNewPassword": "Xác nhận mật khẩu mới", "confirmNewPasswordPlaceholder": "Nhập lại mật khẩu mới", "verifyBtn": "Xác thực", "verifying": "Đang xác thực...", "verified": "✓ Mật khẩu đã xác thực", "incorrectPassword": "Mật khẩu hiện tại không đúng.", "passwordRequired": "Vui lòng nhập mật khẩu hiện tại.", "enterNewPasswordBelow": "Nhập mật khẩu mới bên dưới.", "passwordMismatch": "Mật khẩu không khớp.", "updatePassword": "Cập nhật mật khẩu", "updating": "Đang cập nhật...", "passwordUpdated": "Mật khẩu đã được cập nhật thành công!"},
  "friends": {"title": "Bạn bè", "friendsTab": "Bạn bè", "blockedTab": "Người dùng bị chặn", "friendsComingSoon": "Tính năng bạn bè sắp ra mắt.", "noBlocked": "Không có người dùng nào bị chặn.", "unblock": "Bỏ chặn", "unblocking": "Đang xử lý...", "loginToView": "Đăng nhập để xem bạn bè và người dùng bị chặn."},
  "report": {"title": "Báo cáo", "reason": "Lý do", "reasonPlaceholder": "Chọn lý do", "description": "Chi tiết (tùy chọn)", "descriptionPlaceholder": "Mô tả chi tiết vấn đề...", "attachImage": "📷 Đính kèm hình ảnh", "removeImage": "× Xóa", "submit": "Gửi báo cáo", "submitting": "Đang gửi...", "cancel": "Hủy", "successTitle": "Báo cáo đã được gửi.", "successDesc": "Chúng tôi sẽ xem xét và xử lý.", "duplicatePost": "Bạn đã báo cáo bài viết này rồi.", "duplicateComment": "Bạn đã báo cáo bình luận này rồi.", "errorGeneric": "Đã xảy ra lỗi. Vui lòng thử lại.", "selectReason": "Vui lòng chọn lý do báo cáo.", "reasons": {"hate": "Thù hận / Ngôn ngữ xúc phạm", "sexual": "Quấy rối tình dục", "spam": "Spam / Quảng cáo", "scam": "Lừa đảo / Hoạt động đáng ngờ", "misinformation": "Thông tin sai", "privacy": "Vi phạm quyền riêng tư", "illegal": "Nội dung bất hợp pháp / nguy hiểm", "other": "Khác"}},
  "help": {"title": "Trợ giúp & Hỗ trợ", "faqTitle": "Câu hỏi thường gặp", "shareIdeasTitle": "Chia sẻ ý tưởng", "shareIdeasDesc": "Bạn có ý tưởng về tính năng hoặc dịch vụ? Hãy cho chúng tôi biết! Ý tưởng hay sẽ được triển khai và nhận phần thưởng.", "shareIdeasBtn": "Chia sẻ ý tưởng", "needHelpTitle": "Cần thêm hỗ trợ?", "needHelpDesc": "Không tìm thấy những gì bạn cần? Liên hệ nhóm của chúng tôi bất cứ lúc nào.", "contactBtn": "Liên hệ nhóm", "faqs": {"q1": "ANNYEONG có thực sự miễn phí không?", "a1": "Truy cập cộng đồng và thông tin cơ bản hoàn toàn miễn phí. Một số dịch vụ cao cấp có thể mất phí, nhưng tư vấn ban đầu luôn miễn phí.", "q2": "Mất bao lâu để nhận được hỗ trợ?", "a2": "Chúng tôi phản hồi hầu hết câu hỏi trong vòng 1-2 giờ. Trường hợp khẩn cấp được ưu tiên.", "q3": "Tôi cần tài liệu gì cho visa?", "a3": "Tùy thuộc vào loại visa. Tham gia cộng đồng hoặc liên hệ chúng tôi để được hướng dẫn cụ thể.", "q4": "Tôi có thể dùng ANNYEONG trước khi đến Hàn Quốc không?", "a4": "Hoàn toàn có thể! Nền tảng của chúng tôi giúp bạn chuẩn bị trước khi đến.", "q5": "Hỗ trợ những ngôn ngữ nào?", "a5": "Chúng tôi hỗ trợ tiếng Hàn, Anh, Trung, Nhật, Việt. Sắp thêm ngôn ngữ mới!"}, "shareIdea": {"title": "💡 Chia sẻ ý tưởng", "ideaTitle": "Tiêu đề", "ideaTitlePlaceholder": "Mô tả ý tưởng trong một câu", "featureArea": "Lĩnh vực tính năng", "featureAreaPlaceholder": "Chọn...", "description": "Mô tả", "descriptionPlaceholder": "Mô tả chi tiết ý tưởng...", "photo": "Ảnh (tùy chọn)", "uploadImage": "📷 Tải ảnh lên", "submitBtn": "Gửi ý tưởng", "submitting": "Đang gửi...", "fillRequired": "Vui lòng điền đầy đủ các trường bắt buộc.", "submitFailed": "Gửi thất bại. Vui lòng thử lại.", "successTitle": "Cảm ơn ý tưởng của bạn!", "successDesc": "Chúng tôi sẽ xem xét sớm.", "featureOptions": {"community": "Cộng đồng", "service": "Dịch vụ", "other": "Khác"}}, "needHelp": {"title": "🤝 Cần thêm hỗ trợ?", "ideaTitle": "Tiêu đề", "ideaTitlePlaceholder": "Tóm tắt ngắn gọn vấn đề", "details": "Chi tiết", "detailsPlaceholder": "Mô tả những gì bạn cần giúp đỡ...", "contact": "Email / Liên hệ (tùy chọn)", "contactPlaceholder": "Chúng tôi có thể liên hệ bạn ở đâu?", "photo": "Ảnh (tùy chọn)", "uploadImage": "📷 Tải ảnh lên", "sendBtn": "Gửi yêu cầu", "sending": "Đang gửi...", "fillRequired": "Vui lòng điền đầy đủ các trường bắt buộc.", "sendFailed": "Gửi thất bại. Vui lòng thử lại.", "successTitle": "Yêu cầu của bạn đã được gửi!", "successDesc": "Nhóm của chúng tôi sẽ liên hệ sớm.", "topics": {"visa": "Visa / Cư trú", "housing": "Nhà ở", "job": "Việc làm / Công việc", "school": "Trường học / Giáo dục", "health": "Sức khỏe / Bệnh viện", "other": "Khác"}}},
  "signup": {"title": "Đăng ký", "email": "Email", "password": "Mật khẩu", "nickname": "Biệt danh", "country": "Quốc gia", "preferredLanguage": "Ngôn ngữ ưa thích", "purpose": "Mục đích", "status": "Trạng thái hiện tại", "check": "Kiểm tra", "signingUp": "Đang đăng ký...", "cancel": "Hủy", "emailRequired": "Vui lòng xác nhận email có thể dùng được.", "nicknameRequired": "Vui lòng xác nhận biệt danh có thể dùng được.", "passwordRequired": "Vui lòng nhập mật khẩu.", "failed": "Đăng ký thất bại. Vui lòng thử lại.", "success": "Đăng ký thành công.", "emailCheckFailed": "Kiểm tra email thất bại. Vui lòng thử lại.", "nicknameCheckFailed": "Kiểm tra biệt danh thất bại. Vui lòng thử lại.", "enterEmail": "Vui lòng nhập email.", "enterNickname": "Vui lòng nhập biệt danh.", "confirmLanguageTitle": "Xác nhận lựa chọn ngôn ngữ", "confirm": "Xác nhận", "purposeOptions": {"community": "Cộng đồng", "service": "Dịch vụ", "information": "Thông tin"}, "statusOptions": {"living": "Đang sống ở Hàn Quốc", "planning": "Dự định chuyển đến Hàn Quốc"}},
  "findId": {"title": "Tìm tài khoản", "desc": "Vui lòng nhập biệt danh bạn đã dùng khi đăng ký.", "nicknamePlaceholder": "Biệt danh", "find": "Tìm", "searching": "Đang tìm...", "close": "Đóng", "enterNickname": "Vui lòng nhập biệt danh.", "notFound": "Không tìm thấy biệt danh. Vui lòng kiểm tra và thử lại.", "failed": "Tìm tài khoản thất bại. Vui lòng thử lại.", "yourEmail": "Email của bạn"},
  "resetPassword": {"title": "Đặt lại mật khẩu", "step1Desc": "Nhập email liên kết với tài khoản của bạn.", "codeSentTo": "Mã xác thực đã gửi đến", "step2Desc": "Nhập mã xác thực đã gửi đến email của bạn.", "step3Desc": "Nhập mật khẩu mới.", "newPassword": "Mật khẩu mới", "confirmPassword": "Xác nhận mật khẩu", "sendCode": "Gửi mã xác thực", "sending": "Đang gửi...", "back": "Quay lại", "verify": "Xác thực", "verifying": "Đang xác thực...", "resetBtn": "Đặt lại mật khẩu", "resetting": "Đang đặt lại...", "successTitle": "Đặt lại mật khẩu thành công", "successDesc": "Mật khẩu của bạn đã được đặt lại thành công. Vui lòng đăng nhập bằng mật khẩu mới.", "enterEmail": "Vui lòng nhập email.", "enterCode": "Vui lòng nhập mã xác thực.", "codeLength": "Mã xác thực phải có 8 chữ số.", "codeExpired": "Mã xác thực đã hết hạn. Vui lòng yêu cầu lại.", "codeInvalid": "Mã xác thực không hợp lệ. Vui lòng kiểm tra lại.", "sendFailed": "Gửi mã xác thực thất bại. Vui lòng thử lại.", "verifyFailed": "Xác thực thất bại. Vui lòng thử lại.", "enterNewPassword": "Vui lòng nhập mật khẩu mới.", "passwordMismatch": "Mật khẩu không khớp.", "resetFailed": "Đặt lại mật khẩu thất bại. Vui lòng thử lại."},
  "writePost": {"title": "Viết bài", "category": "Danh mục", "categoryPlaceholder": "Chọn danh mục", "postTitle": "Tiêu đề", "titlePlaceholder": "Nhập tiêu đề", "content": "Nội dung", "contentPlaceholder": "Viết bài của bạn...", "photo": "Ảnh (tùy chọn)", "uploadImage": "📷 Tải ảnh lên", "submit": "Gửi", "saving": "Đang lưu...", "fillRequired": "Vui lòng điền đầy đủ các trường bắt buộc.", "failed": "Lưu bài viết thất bại."},
  "languages": {"en": "Tiếng Anh", "ko": "Tiếng Hàn", "zh": "Tiếng Trung", "ja": "Tiếng Nhật", "es": "Tiếng Tây Ban Nha", "vi": "Tiếng Việt"}
}

locales = {
    'en': EN,
    'ko': KO,
    'zh': ZH,
    'ja': JA,
    'es': ES,
    'vi': VI,
}

for code, data in locales.items():
    path = os.path.join(BASE, code, 'common.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'✓ {code} written ({len(json.dumps(data))} chars)')

print('All locale files updated.')
